version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node --version
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
      - echo $ACCOUNT_ID
      - >-
        zip -r ceoa-7-examples.zip ./webapp -j -x '*.git*'
      - >-
        aws s3 sync ceoa-7-examples.zip s3://$PIPELINE_BUCKET
artifacts:
  files:
    - '**/*'
